### ISSUE TITLE
Notice: Undefined offset: 0 in xx/plugins/craftgate-payment-gateway/craftgate-payment-gateway.php on line 383

### ISSUE THREAD

**Issue by antikadam** [craftgate/craftgate-woocommerce-gateway#14]
Selamlar.. Ödeme sayfasının hemen üzerinde böyle bir hata alıyorum..

**Comment by onurpolattimur** [comment]
Selamlar, geri bildiriminiz için çok teşekkürler. Hatanın çözümü için ilgili geliştirmeleri tamamladık, 1.0.8 versiyonu ile beraber fixlenmiş olacak.
