### ISSUE TITLE
Notice: Undefined index: cg-lang-header in /wp-content/plugins/craftgate-payment-gateway/includes/lib/craftgate/src/Adapter/BaseAdapter.php on line 58

### ISSUE THREAD

**Issue by antikadam** [craftgate/craftgate-woocommerce-gateway#15]
Ödeme sayfasının hemen üzerinde az önce ki hataya benzer başka bir hata daha aldım..

**Comment by onurpolattimur** [comment]
Selamlar, geri bildiriminiz için çok teşekkürler. Hatanın çözümü için ilgili geliştirmeleri tamamladık, 1.0.8 versiyonu ile beraber fixlenmiş olacak.
